# This document provides the default settings for the entire site.
# Settings can be overridden by including additional options in YML headers on 
# specific pages.

project:
  type: website

website:
  title: "Fancy Guesses"
  site-url: https://fancy-guesses.co
  description: "A place for playing with data science workflows"
  search: false
  navbar: 
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - beginnings.qmd

format:
  html:
    theme: sketchy
    css: _assets/styles.css
    toc: true
    backgroundcolor: "#FFFAED"
    

editor: visual

