project:
  type: website

website:
  title: "Fancy Guesses"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: sketchy
    css: styles.css
    toc: true
    backgroundcolor: "#FFFAED"
    

editor: visual

