# This document provides the default settings for the entire site.
# Settings can be overridden by including additional options in YML headers on 
# specific pages.

project:
  type: website
  output-dir: _docs

website:
  title: "Fancy Guesses"
  site-url: https://fancy-guesses.co
  description: "A place for playing with data science workflows"
  search: false
  sidebar: false
  navbar: 
    css: _assets/styles.css
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - beginnings.qmd
    collapse: true
    collapse-below: md
    title: FG
  open-graph:
    locale: en_US
    site-name: Fancy Guesses

format:
  html:
    css: _assets/styles.css
    toc: true
    backgroundcolor: "#FFFAED"
    mainfont: Yantramanav

    

editor: visual




