project:
  type: website

website:
  title: "Fancy Guesses"
  search: false
  navbar: 
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - beginnings.qmd
  sidebar: 
    style: floating
    search: true
    contents: 
      - section: "Stuff"
        contents: 
          - about.qmd
      - section: "Things"
        contents: 
          - beginnings.qmd

format:
  html:
    theme: sketchy
    css: styles.css
    toc: true
    backgroundcolor: "#FFFAED"
    

editor: visual

